<?php

require_once dirname(__FILE__) . '/../../../application/models/Action.php';

/**
 * Test class for Application_Model_Action.
 * Generated by PHPUnit on 2012-09-18 at 03:21:14.
 */
class Application_Model_ActionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Application_Model_Action
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Application_Model_Action(array('name' => 'a-name', 'description' => 'a-description', 'title' => 'a-title'));
  }

  public function testCheckDefaultIdIsNull() {
    $this->assertNull($this->object->getId());
  }

  public function testGetName() {
    $this->assertEquals('a-name', $this->object->getName());
  }

  public function testGetDescription() {
    $this->assertEquals('a-description', $this->object->getDescription());
  }

  public function testGetTitle() {
    $this->assertEquals('a-title', $this->object->getTitle());
  }

  public function testSetName() {
    $this->object->setName('a-new-name');
    $this->assertEquals('a-new-name', $this->object->getName());
  }

  public function testSetTitle() {
    $this->object->setTitle('a-new-title');
    $this->assertEquals('a-new-title', $this->object->getTitle());
  }

  public function testSetDescription() {
    $this->object->setDescription('a-new-description');
    $this->assertEquals('a-new-description', $this->object->getDescription());
  }
}
?>