<?php

require_once dirname(__FILE__) . '/../../../application/models/Setting.php';

/**
 * Test class for Application_Model_Setting.
 * Generated by PHPUnit on 2012-09-18 at 03:25:40.
 */
class Application_Model_SettingTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Application_Model_Setting
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Application_Model_Setting('a-key', 'a-value', 'a-label');
  }

  public function testGetSettingKey() {
    $this->assertEquals('a-key', $this->object->getSettingKey());
  }

  public function testGetValue() {
    $this->assertEquals('a-value', $this->object->getValue());
  }

  public function testGetLabel() {
    $this->assertEquals('a-label', $this->object->getLabel());
  }

  public function testLabelCanBeChanged() {
    $this->object->setLabel('a-different-label');
    $this->assertEquals('a-different-label', $this->object->getLabel());
  }

  public function testValueCanBeChanged() {
    $this->object->setValue('a-different-value');
    $this->assertEquals('a-different-value', $this->object->getValue());
  }

}

?>