<table cellpadding="0" cellspacing="0" class="default"> 
  <thead>
    <tr>
      <th><?php echo $this->translate("Title"); ?></th>
      <th style="width: 200px;"><?php echo $this->translate("Name"); ?></th>
      <th class="fit-content"><?php echo $this->translate("Actions"); ?></th>
    </tr>
  </thead>
  <tbody>
    <?php if(count($this->paginator)): ?>
      <?php foreach($this->paginator as $state): ?>
        <tr>
          <td data-label="<?php echo $this->translate("Name"); ?>"><?php echo $state->getTitle(); ?></td>
          <td data-label="<?php echo $this->translate("Title"); ?>"><?php echo $state->getName(); ?></td>
          <td data-label="<?php echo $this->translate("Actions"); ?>" class="fit-content"><?php echo $this->partial('partials/action-dropdown.phtml', array('actions'=>$state->actions)); ?></td>
        </tr>
      <?php endforeach; ?>
    <?php else: ?>
      <tr>
        <td colspan="4" class="no-label"><?php echo $this->translate("No states found."); ?></td>
      </tr>
    <?php endif; ?>
  </tbody>
</table> 
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>

<a class="btn btn-primary" href="/setting/create-state"><i class="icon-database-add icon-fam"></i><?php echo $this->translate("Create a new state"); ?></a>
