<?php 
    // temporaly using the list of documents	
	//
	echo "List of reporters";
	//
	//echo $this->simForm;
	
?>


<?php
    $this->title = $this->translate("List of reporters");
    $this->headTitle($this->title);
?>
<table cellpadding="0" cellspacing="0" class="default"> 
  <tr>
    <th><?php echo $this->translate("Title"); ?></th>
    <th style="width: 100px;"><?php echo $this->translate("Actions"); ?></th>
  </tr>
  <?php 
  $i = 0;
  $reportDirectory = "storage" . DIRECTORY_SEPARATOR . "reports" . DIRECTORY_SEPARATOR;
  $report_name = "test_report.txt";
 
  $report_path = APPLICATION_PATH . DIRECTORY_SEPARATOR . $reportDirectory. "$report_name";
 
  
 ?>
 
    
  <tr <?php echo ($i++ %2 == 0) ? "class=\"even\"" : ""; ?>>
    <td><a href="<?php echo $report_path; ?>"><?php echo $report_name;?></a></td>
    
  </tr>
  
</table>

<?php
//$data["content"] = file_get_content($report_path);
  //$lines = explode('<br />',$content);
?>
<p>
<a href="/simtext/compare"><?php echo $this->translate("Compare"); ?></a>
</p>