<table cellpadding="0" cellspacing="0" class="default"> 
  <thead>
    <tr>
      <th><?php echo $this->translate("Title"); ?></th>
      <th class="state-column"><?php echo $this->translate("State"); ?></th>
      <th class="fit-content"><?php echo $this->translate("Actions"); ?></th>
   </tr>
  </thead>
  <tbody>
    <?php if(count($this->paginator)): ?>
      <?php foreach($this->paginator as $report): ?>
        <tr>
          <?php if($report->getState()->getName() == "generated"){ ?>
            <td data-label="<?php echo $this->translate("Title"); ?>"><a href="<?php echo $report->getDirectLink(); ?>"><?php echo $report->getTitle(); ?></a></td>
          <?php }else{ ?>
            <td data-label="<?php echo $this->translate("Title"); ?>"><?php echo $report->getTitle(); ?></td>
          <?php } ?>
          <td data-label="<?php echo $this->translate("State"); ?>"><?php echo $report->outputState; ?></td>
          <td data-label="<?php echo $this->translate("Actions"); ?>"><?php echo $this->partial('partials/action-dropdown.phtml', array('actions'=>$report->actions)); ?></td>
        </tr>
      <?php endforeach; ?>
    <?php else: ?>
      <tr>
        <td colspan="3" class="no-label"><?php echo $this->translate("No reports found."); ?></td>
      </tr>
    <?php endif; ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>