<?php
$this->title = $this->translate("Fragment");
$this->headTitle($this->title);
?>

<?php echo $this->translate("Name"); ?>: <?php echo $this->fragment->getTitle(); ?><br />
<?php echo $this->translate("Type"); ?>: <?php echo $this->fragment->getType()->getName(); ?><br/>
<?php echo $this->translate("Source"); ?>: //<br/>
<div style="text-align: right; padding-top: 15px; padding-bottom: 5px;">
<label for="compareWithNoColor">Compare with no color</label>
<input type="checkbox" name="compare" id="compareWithNoColor" checked="checked" value="<?php echo $this->fragment->getId(); ?>" />
</div>
<div class="document-page diff clearfix">
  <div class="src-wrapper">
    <h3><?php echo $this->translate("Fragment"); ?></h3>
    <p>From: page <?php echo $this->plag->getLineFrom()->getPage()->getPageNumber(); ?>, line <?php echo $this->plag->getLineFrom()->getLineNumber(); ?></p>
    <p>To: page <?php echo $this->plag->getLineTo()->getPage()->getPageNumber(); ?>, line <?php echo $this->plag->getLineTo()->getLineNumber(); ?></p>    
    <div id="candidateText"><?php echo $this->content['plag']; ?></div>
  </div>
  <div class="src-wrapper">
    <h3><?php echo $this->translate("Source"); ?></h3>
    <p>From: page <?php echo $this->source->getLineFrom()->getPage()->getPageNumber(); ?>, line <?php echo $this->source->getLineFrom()->getLineNumber(); ?></p>
    <p>To: page <?php echo $this->source->getLineTo()->getPage()->getPageNumber(); ?>, line <?php echo $this->source->getLineTo()->getLineNumber(); ?></p>
    <div id="sourceText"><?php echo $this->content['source']; ?></div>
  </div>
</div>

<?php echo $this->translate("Note"); ?>: <?php echo $this->fragment->getNote(); ?>
<div>
  <div class="smork-btn light">
    <a href="#" for="comments-wrapper-<?php echo $this->fragment->getId(); ?>" class="toggle-comments"><span class="comments-icon">Show comments</span></a>
  </div>
  <br /><br />
  <?php echo $this->partial('partials/comments.phtml', array('sourceId'=>$this->fragment->getId(), 'hidden'=>true)); ?>
</div>