<?php
$this->title = $this->translate("Recent activity");
$this->headTitle($this->title);
?>
<div id="activity-stream">
<?php foreach($this->paginator as $notification): ?>
  <div class="activity-item">
    <div class="activity">
      <div class="image"><img class="avatar-small" src="<?php echo $notification->getUser()->getAvatar(); ?>" /></div>
      <div class="details">
        <div class="title-wrapper">
          <h4>
            <span class="title <?php echo $notification->getSource()->getIconClass(); ?>"><?php echo sprintf($notification->getTitle(), "<a href=\"" . $notification->getSource()->getDirectLink() . "\">" . $notification->getSource()->getDirectName() . "</a>"); ?></span> <span class="user"><?php echo $notification->getUser()->getUsername();?>, <?php echo Unplagged_Helper::humanTiming($notification->getCreated()); ?> </span>
          </h4>
          <div class="links"  style="text-align: right">
          <div class="smork-btn light">
            <a href="#" for="comments-wrapper-<?php echo $notification->getId(); ?>" class="toggle-comments"><span class="comments-icon">Show comments</span></a>
          </div>
        </div>
        </div>
        <p><?php echo $notification->getMessage(); ?></p>
        
      </div>
    </div>
    <?php echo $this->partial('partials/comments.phtml', array('sourceId' => $notification->getId(), 'hidden' => true)); ?>
  </div>
  <?php endforeach; ?>
</div>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>