<?php
/*
 * Unplagged - The plagiarism detection cockpit.
 * Copyright (C) 2012 Unplagged
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php if($this->address): ?>
<p><?php echo $this->address; ?></p>
<?php endif; ?>
<?php if($this->telephone || $this->email): ?>
<h2><?php echo $this->translate('Contact'); ?>:</h2>
<dl>
  <dt><?php echo $this->translate('Telephone'); ?>:</dt>
  <dd><?php echo $this->telephone; ?></dd>
  <dt>E-Mail:</dt>
  <dd><?php echo $this->email; ?></dd>
</dl>
<?php endif; ?>