<?php
$languageString = Zend_Registry::getInstance()->Zend_Locale->getLanguage();
$defaultConfig = Zend_Registry::getInstance()->config->default;
$applicationName = $defaultConfig->applicationName;
$this->title = $this->translate('Welcome to %s', $applicationName);
$this->headTitle($this->title);
?>
<div class="welcome-message well">
<?php if($languageString === 'de'): ?>
  <?= $defaultConfig->welcomeMessage->de ?>
<?php else: ?>
  <?= $defaultConfig->welcomeMessage->default ?>
<?php endif; ?>
</div>
<?php if(count($this->barcodes > 0)): ?>
  <div class="barcodes-big">  
    <?php foreach($this->barcodes as $barcode): ?>
      <h4><?php echo $barcode['title']; ?></h4>
      <?php echo $barcode['graphic']; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>