<?php
/**
 * This file was autogenerated by the Unplagged Installer. If you know what you are doing, 
 * it is possible to change the below configuration values, it is however recommended
 * to use the Installer, because your changes may be overriden when the installer is used
 * again.
 */

return array (
);