<?php
return array(
    'hydrator'=>'Zend\Stdlib\Hydrator\ArraySerializable',
    'name'=>'create-case',
    'elements'=>array(
        array(
            'spec'=>array(
                'type'=>'Zend\Form\Element\Text',
                'name'=>'case-name',
                'attributes'=>array(
                    'placeholder'=>'Guttenberg',
                    'required'=>'required',
                ),
                'options'=>array(
                    'label'=>'Name',
                    'description'=>'Usually the title or author of the document you want to investigate.',
                ),
            ),
        ),
        array(
            'spec'=>array(
                'type'=>'Zend\Form\Element\Text',
                'name'=>'case-alias',
                'attributes'=>array(
                    'placeholder'=>'ktg',
                    'required'=>'required',
                ),
                'options'=>array(
                    'label'=>'Alias',
                    'description'=>"This will be used in public places as long as the case wasn't published to avoid giving away sensitive information through the actual name.",
                ),
            ),
        ),
        array(
            'spec'=>array(
                'name'=>'case-description',
                'type'=>'Zend\Form\Element\Textarea',
                'attributes'=>array(
                    'placeholder'=>'Your description..',
                ),
                'options'=>array(
                    'label'=>'Description',
                    'description'=>'The marketing message if you want other users to engage in this case, or simply a small reminder for yourself about the motivation for this.',
                ),
            ),
        ),
        array(
            'spec'=>array(
                'name'=>'submit-btn',
                'type'=>'Zend\Form\Element\Submit',
                'attributes'=>array(
                    'value'=>'Create',
                ),
                'options'=>array(
                    'primary'=>true,
                ),
            )
        ),
        array(
            'spec'=>array(
                'name'=>'reset-btn',
                'attributes'=>array(
                    'type'=>'reset',
                    'value'=>'Reset',
                ),
            )
        )
    ),
    'display_options'=>array(
        'class'=>'page-form',
        'elements'=>array(
            'case-name'=>array(
                'class'=>'input-xlarge',
                'required'=>true,
            ),
            'case-alias'=>array(
                'class'=>'input-xlarge',
                'required'=>true,
            ),
            'case-description'=>array(
                'class'=>'',
                'rows'=>5,
                'required'=>false,
            ),
            'reset-btn'=>array(
                'class'=>'pull-right',
            ),
            'submit-btn'=>array(
                'class'=>'btn-large',
            ),
        ),
    ),
    'input_filter'=>array(
        'case-name'=>array(
            'required'=>true,
            'filters'=>array(
                array('name'=>'\Zend\Filter\StringTrim'),
                array('name'=>'\Zend\Filter\StripTags'),
            ),
            'validators'=>array(
                array('name'=>'\Zend\Validator\StringLength', 'options'=>array('min'=>3, 'message'=>'The name of the case must be at least three characters long.')),
            ),
        ),
        'case-alias'=>array(
            'required'=>true,
            'filters'=>array(
                array('name'=>'\Zend\Filter\StringTrim'),
                array('name'=>'\Zend\Filter\StripTags'),
            ),
            'validators'=>array(
                array('name'=>'\Zend\Validator\StringLength', 'options'=>array('min'=>3, 'message'=>'The name of the case must be at least three characters long.')),
            ),
        ),
        'case-description'=>array(
            'required'=>false,
            'filters'=>array(
                array('name'=>'\Zend\Filter\StringTrim'),
                array('name'=>'\Zend\Filter\StripTags'),
            ),
        ),
    ),
);
