<nav id="right-nav">
  <h4>Aktuelles und Kontroverses</h4>
  <ul>
    <li><a href="#">News 1<span class="count">3</span></a></li>
    <li><a href="#">News 1<span class="count">3</span></a></li>
    <li><a href="#">News 1<span class="count">3</span></a></li>
  </ul>
  <br />
  <h4>Berichte und Mitteilungen</h4>
  <ul>
    <li><a href="#">News 1<span class="count">3</span></a></li>
    <li><a href="#">News 1<span class="count">3</span></a></li>
    <li><a href="#">News 1<span class="count">3</span></a></li>
  </ul>
</nav>