<nav id="right-nav">
  <ul class="nav nav-list">
    <li class="nav-header">
  <?php echo $this->translate("Latest cases"); ?></li>
  
    <?php foreach ($this->cases as $case): ?>
    <?php $barcode = null; ?>
    <li>
      <a href="#"><?php echo $case->getPublishableName(); ?> <span class="badge badge-light"><?php echo $case->getPlagiarismPercentage(); ?> %</span>
        <div class="barcode">
          <?php $barcode = $case->getBarcode(100, 25, 25, false, '%'); ?>
          <?php echo ($barcode) ? $barcode->render() : '<i>no target available for barcode</i>'; ?>
        </div>
      </a>
    </li>
    <?php endforeach; ?>
  </ul>
</nav>