<nav id="right-nav">
  <h4><?php echo $this->translate("Latest cases"); ?></h4>
  <ul>
    <?php foreach ($this->cases as $case): ?>
    <li>
      <a href="#"><?php echo $case->getPublishableName(); ?> <span class="count"><?php echo $case->getPlagiarismPercentage(); ?> %</span>
        <div class="barcode">
        <img src="/images/plag_barcode.png" alt="barcode"/>
        </div>
      </a>
    </li>
    <?php endforeach; ?>
  </ul>
</nav>