<nav id="right-nav">
  <h4>Actions</h4>
  <ul>
    <li>
      <a href="<?php echo "/document_fragment/show/id/" . $this->fragmentId;     ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/page.png'); ?>" title="<?php echo $this->translate("Show"); ?>" /><span><?php echo $this->translate("Show"); ?></span>
      </a>
    </li>
        <li>
      <a href="<?php echo "/document_fragment/edit/id/" . $this->fragmentId;     ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/pencil.png'); ?>" title="<?php echo $this->translate("Edit"); ?>" /><span><?php echo $this->translate("Edit"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_fragment/delete/id/" . $this->fragmentId;     ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/delete.png'); ?>" title="<?php echo $this->translate("Remove"); ?>" /><span><?php echo $this->translate("Remove"); ?></span>
      </a>
    </li>
  </ul>
  
  <h4>Links</h4>
  <ul>
    <li>
      <a href="<?php echo "/document_fragment/changelog/id/" . $this->fragmentId;     ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/table_relationship.png'); ?>" title="<?php echo $this->translate("Changelog"); ?>" /><span><?php echo $this->translate("Changelog"); ?></span>
      </a>
    </li>
  </ul>
</nav>