<nav id="right-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Actions</li>
    <li>
      <a href="<?php echo "/document_page/show/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/page.png'); ?>" title="<?php echo $this->translate("Show"); ?>" /><span><?php echo $this->translate("Show"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/edit/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/pencil.png'); ?>" title="<?php echo $this->translate("Edit"); ?>" /><span><?php echo $this->translate("Edit"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/delete/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/delete.png'); ?>" title="<?php echo $this->translate("Remove"); ?>" /><span><?php echo $this->translate("Remove"); ?></span>
      </a>
    </li>
    <li>
      <a href="#" class="create-fragment">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/textfield_add.png'); ?>" title="<?php echo $this->translate("Create fragment"); ?>" /><span><?php echo $this->translate("Create fragment"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/de-hyphen/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/text_padding_right.png'); ?>" title="<?php echo $this->translate("De-hyphen"); ?>" /><span><?php echo $this->translate("De-hyphen"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/stopwords/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/zoom.png'); ?>" title="<?php echo $this->translate("Non-stopword identification"); ?>" /><span><?php echo $this->translate("Non-stopword identification"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/simtext/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/table_row_delete.png'); ?>" title="<?php echo $this->translate("Simtext"); ?>" /><span><?php echo $this->translate("Simtext"); ?></span>
      </a>
    </li>
    <li class="nav-header">Links</li>
    <li>
      <a href="<?php echo "/document_fragment/list/page/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/textfield_rename.png'); ?>" title="<?php echo $this->translate("Fragments"); ?>" /><span><?php echo $this->translate("Fragments"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/detection-reports/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/report_magnify.png'); ?>" title="<?php echo $this->translate("Plagiarism Detection Reports"); ?>" /><span><?php echo $this->translate("Plagiarism Detection Reports"); ?></span>
      </a>
    </li>
        <li>
      <a href="<?php echo "/document_page/simtext-reports/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/table_row_delete.png'); ?>" title="<?php echo $this->translate("Simtext Reports"); ?>" /><span><?php echo $this->translate("Simtext Reports"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/changelog/id/" . $this->pageId; ?>">
        <img class="icon" src="<?php echo $this->baseUrl('images/icons/table_relationship.png'); ?>" title="<?php echo $this->translate("Changelog"); ?>" /><span><?php echo $this->translate("Changelog"); ?></span>
      </a>
    </li>
  </ul>
</nav>