<h1>Liste der hochgeladenen Dateien</h1>
<li>
  <?php foreach($this->listFiles as $file): ?> 
    <?php if($file != "." && $file != ".."): ?>
      <form method="POST" action="/uploadlist/uploadlist">
        <?php $this->file = $file ?>
        <ul>
          <?php echo $file ?> &nbsp;
          <input type="hidden" value="<?php echo $file ?>" name="file"/>
          [&nbsp; Target: <input type="checkbox" value="id"/>]
          <input type="submit" value="delete" />                
        </ul>
      </form>

    <?php endif; ?>
  <?php endforeach; ?>
  <a href="/upload/upload">hochladen</a>
</li>