<!doctype html>
<!--[if lte IE 7]> <html class="no-js ie7 oldie"> <![endif]-->
<!--[if IE 8]> <html class="no-js ie8 oldie"> <![endif]-->
<!--[if IE 9]> <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <?php echo $this->headMeta(); ?>
    <!-- Design based on http://www.premiumpixels.com/ -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle(); ?>
    <?php
    echo $this->headLink()
        ->appendStylesheet($this->baseUrl('style/jquery.lightbox-0.5.css'))
        ->appendStylesheet($this->baseUrl('style/styles.css'))
        ->prependStylesheet($this->baseUrl('style/flick/jquery-ui-1.8.17.custom.css'))
        ->prependStylesheet($this->baseUrl('style/bootstrap.min.css'));
    ?>
    <!-- Modernizr needs to stay in the head to work properly -->
    <script src="<?php echo $this->baseUrl('js/libs/modernizr-2.5.3.min.js'); ?>"></script>
  </head>
  <body>
    <noscript><div class="alert-danger top-alert"><div class="alert alert-danger"><h4 class="alert-heading"><?php echo $this->translate('Attention!'); ?></h4><p><?php echo $this->translate('Unfortunately JavaScript is currently not supported or is disabled in your browser. Please enable JavaScript for full functionality.'); ?></p></div></div></noscript>
    <!-- Prompt users of IE 7 and lower to install Chrome Frame. -->
    <!--[if lt IE 8]><div class="alert-danger top-alert"><div class="alert alert-danger"><p><?php echo $this->translate('Your browser is'); ?><em> <?php echo $this->translate('ancient!'); ?></em> <a href="http://browsehappy.com/"><?php echo $this->translate('Upgrade to a different browser'); ?></a> <?php echo $this->translate('or'); ?> <a href="http://www.google.com/chromeframe/?redirect=true"><?php echo $this->translate('install Google Chrome Frame'); ?></a> <?php echo $this->translate('to experience this site.'); ?></p></div></div><![endif]-->
    <header role="toolbar">
      <div class="content clearfix">
        <?php if(Zend_Auth::getInstance()->hasIdentity() && $this->me && $this->me->getUsername() !== 'guest'): ?>
          <div class="user-box">
            <img class="avatar" src="<?php echo Unplagged_Helper::getAvatarPath($this->me); ?>" />
            <div class="dropdown-button hoverable user-menu">
              <a class="button" href="<?php echo $this->baseUrl('user/edit'); ?>"><?php echo $this->me->getUsername(); ?><span class="arrow-down"></span></a>
              <ul>
                <li><a href="<?php echo $this->baseUrl('auth/logout'); ?>"><?php echo $this->translate("Logout"); ?></a></li>
                <li><a href="<?php echo $this->baseUrl('user/edit'); ?>"><?php echo $this->translate("Edit Profile"); ?></a></li>
                <li><a href="<?php echo $this->baseUrl('user/settings'); ?>"><?php echo $this->translate("Settings"); ?></a></li>
              </ul>
            </div>
          </div>
        <?php else: ?>
          <div class="login-register-box">
            <a href="<?php echo $this->baseUrl('register'); ?>"><?php echo $this->translate("Register now"); ?></a>
            <span><?php echo $this->translate('or') . ' '; ?></span>
            <a href="<?php echo $this->baseUrl('login'); ?>"><?php echo $this->translate("login"); ?></a>
          </div>
        <?php endif; ?>
        <div class="case-settings-box clearfix">
          <?php
          $currentLabel = '';
          $currentValue = null;
          if($this->me->getCurrentCase() instanceof Application_Model_Case){
            $currentLabel = $this->me->getCurrentCase()->getPublishableName();
            $currentValue = $this->me->getCurrentCase()->getId();
          }
          ?>
          <?php if(count($this->cases) > 0): ?>
            <?php if($currentValue): ?>
              <a href="<?php echo $this->baseUrl('case/edit/id/' . $currentValue); ?>"><?php echo $this->translate("Edit Case"); ?></a>
            <?php endif; ?>
            <form class="current-case" method="POST" action="<?php echo $this->baseUrl('user/set-current-case'); ?>">
              <select data-placeholder="<?php echo $this->translate('Select a Case'); ?>" name="case">
                <option></option>
                <?php foreach($this->cases as $case): ?>
                  <option <?php if($case['value'] == $currentValue) echo 'selected'; ?> value="<?php echo $case['value']; ?>"><?php echo $case['label']; ?></option>
                <?php endforeach; ?>
              </select>
              <button class="button">Ok</button>  
            </form>
          <?php endif; ?>
        </div>
      </div>
    </header>
    <div class="pagewrap">
      <header role="banner" class="clearfix">
        <a href="https://github.com/Unplagged/unplagged"><img style="position: absolute; top: -2px; right: -1px; border: 0; width: 129px" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
        <h1 class="ir">Unplagged - The Plagiarism Detection Cockpit</h1>
        <nav><?php echo $this->navigation()->menu(); ?></nav>
      </header>