<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <!-- Design based on http://www.premiumpixels.com/ -->
    <?php echo $this->headMeta(); ?>
    <?php
    echo $this->headLink()
        ->prependStylesheet($this->baseUrl() . '/style/styles.css')
        ->appendStylesheet($this->baseUrl() . '/style/flick/jquery-ui-1.8.17.custom.css')
        ->appendStylesheet($this->baseUrl() . '/js/libs/css/jquery.lightbox-0.5.css');
    ?>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Modernizr needs to stay in the head to work properly -->
    <script src="<?php echo $this->baseUrl('/js/libs/modernizr-2.0.6.min.js'); ?>"></script>
  </head>
  <body>
    <header id="main-header">
      <div id="settings-panel">
        <div class="content">
          <?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
            <div id="avatar"><img src="/images/tmp_avatar.png" /></div>
            <div id="logout-actions">
              <?php echo $this->translate("Welcome") . " " . $this->me->getUsername() . "!"; ?>
              <a href="/auth/logout"><?php echo $this->translate("Logout"); ?></a>
            </div>
            <div id="settings">
              <?php echo $this->translate("Case you're working on"); ?> 
              <div id="current-case-field">
                <?php
                  $value = '';
                  if($this->me->getCurrentCase() instanceof Application_Model_Case){ 
                    $value = 'value="' . $this->me->getCurrentCase()->getPublishableName() . '"'; 
                  }
                ?>
                <select>
                  <option></option>
                </select>
                <input type="text" name="current-case" id="current-case" <?php echo $value; ?> />
                <a href="#" title="<?php echo $this->translate("Unset current case"); ?>" class="clear">x</a></div>
                <a href="/case/list"><?php echo $this->translate("Case Settings"); ?></a><?php /* <img src="/images/tmp_top_icons.png" /> */ ?>
            </div>
          <?php else: ?>
            <div id="login-actions">
              <a href="/user/register"><?php echo $this->translate("Register now"); ?></a>
              <?php echo $this->translate('or') . ' '; ?><a href="/auth/login"><?php echo $this->translate("login"); ?></a>
            </div>
          <?php endif; ?>
          <div style="clear: both"></div>
        </div>
        <span id="dropdown-button" class="arrow-up"></span>
      </div>
    </header>
    <div id="page">
      <header id="header" class="clearfix">
        <h1 class="ir">Unplagged - The Plagiarism Detection Cockpit</h1>
        <?php echo $this->navigation()->menu(); ?>
      </header><?php echo $this->escape($this->title); ?>