<?php $this->headTitle($this->title);
$document = $this->document;
$document_name = $document->getTitle();
$translate = "Bibtex information of document " . $document_name;
 ?>
<h3><?php echo $this->translate($translate); ?></h3>

<div class="default-container">

<h4>Angabe zur Quelle</h4>

<?php 
	
	$bibtex = $document->getBibTex();
	
?>	
<table width="80%" cellpadding="7" cellspacing="3" border="1" rules="none" frame="box">
<tr><td width="100" class="bibtex">Autor:	</td><td><?php echo $bibtex['autor'];?></td></tr>		
<tr><td class="bibtex">Titel:	</td><td><?php echo $bibtex['titel'];?></td></tr>	
	
<?php	$form = $bibtex['form']; ?>

<?php if($form == 'buch'):	?>

<tr><td class="bibtex">Ort:</td><td>	<?php echo $bibtex['ort'];?></td></tr>	

<tr><td class="bibtex">Verlag:	</td><td><?php echo $bibtex['verlag'];?></td></tr>	
<tr><td class="bibtex">Jahr:	</td><td><?php echo $bibtex['jahr'];?></td></tr>	
<tr><td class="bibtex">Anmerkung:</td><td>	<?php echo $bibtex['anmerkung'];?></td></tr>	
<tr><td class="bibtex">ISBN:	</td><td><?php echo $bibtex['isbn'];?></td></tr>	
<tr><td class="bibtex">URL:	</td><td><?php echo $bibtex['url'];?></td></tr>	
<tr><td class="bibtex">inLit:	</td><td><?php echo $bibtex['inlit'];?></td></tr>	
<tr><td class="bibtex">inFN:	</td><td><?php echo $bibtex['infn'];?></td></tr>	

<?php elseif($form == 'periodikum'):	?>

<tr><td class="bibtex">Zeitschrift:	</td><td><?php echo $bibtex['zeitschrift'];?></td></tr>	
<tr><td class="bibtex">Ort:	</td><td><?php echo $bibtex['ort'];?></td></tr>		
<tr><td class="bibtex">Verlag:	</td><td><?php echo $bibtex['verlag'];?></td></tr>	
<tr><td class="bibtex">Jahr:	</td><td><?php echo $bibtex['jahr'];?></td></tr>	
<tr><td class="bibtex">Monat:	</td><td><?php echo $bibtex['monat'];?></td></tr>	
<tr><td class="bibtex">Tag:	</td><td><?php echo $bibtex['tag'];?></td></tr>	
<tr><td class="bibtex">Nummer:	</td><td><?php echo $bibtex['nummer'];?></td></tr>	
<tr><td class="bibtex">Seiten:	</td><td><?php echo $bibtex['seiten'];?></td></tr>	
<tr><td class="bibtex">Anmerkung:	</td><td><?php echo $bibtex['anmerkung'];?></td></tr>	
<tr><td class="bibtex">URL:	</td><td><?php echo $bibtex['url'];?></td></tr>	
<tr><td class="bibtex">inLit:	</td><td><?php echo $bibtex['inlit'];?></td></tr>	
<tr><td class="bibtex">inFN:	</td><td><?php echo $bibtex['infn'];?></td></tr>	

<?php elseif($form == 'aufsatz'):	?>

<tr><td class="bibtex">Sammlung	</td><td><?php echo $bibtex['sammlung'];?></td></tr>	
<tr><td class="bibtex">Hrsg:	</td><td><?php echo $bibtex['hrsg'];?></td></tr>	
<tr><td class="bibtex">Ort:	</td><td><?php echo $bibtex['ort'];?></td></tr>		
<tr><td class="bibtex">Verlag:	</td><td><?php echo $bibtex['verlag'];?></td></tr>	
<tr><td class="bibtex">Jahr:	</td><td><?php echo $bibtex['jahr'];?></td></tr>	
<tr><td class="bibtex">Seiten:	</td><td><?php echo $bibtex['seiten'];?></td></tr>	
<tr><td class="bibtex">Anmerkung:	</td><td><?php echo $bibtex['anmerkung'];?></td></tr>	
<tr><td class="bibtex">ISBN:	</td><td><?php echo $bibtex['isbn'];?></td></tr>	
<tr><td class="bibtex">ISSN:	</td><td><?php echo $bibtex['issn'];?></td></tr>	
<tr><td class="bibtex">URL:	</td><td><?php echo $bibtex['url'];?></td></tr>	
<tr><td class="bibtex">inLit:	</td><td><?php echo $bibtex['inlit'];?></td></tr>		
<tr><td class="bibtex">inFN:	</td><td><?php echo $bibtex['infn'];?></td></tr>	
<?php else:?>

<tr><td class="bibtex">Zeitschrift:	</td><td><?php echo $bibtex['zeitschrift'];?></td></tr>	
<tr><td class="bibtex">Sammlung:	</td><td><?php echo $bibtex['sammlung'];?></td></tr>	
<tr><td class="bibtex">Hrsg:	</td><td><?php echo $bibtex['hrsg'];?></td></tr>	
<tr><td class="bibtex">Beteiligte:	</td><td><?php echo $bibtex['beteiligte'];?></td></tr>	
<tr><td class="bibtex">Ort:	</td><td><?php echo $bibtex['ort'];?></td></tr>		
<tr><td class="bibtex">Verlag:	</td><td><?php echo $bibtex['verlag'];?></td></tr>	
<tr><td class="bibtex">Ausgabe:	</td><td><?php echo $bibtex['ausgabe'];?></td></tr>	
<tr><td class="bibtex">Jahr:	</td><td><?php echo $bibtex['jahr'];?></td></tr>	
<tr><td class="bibtex">Monat:	</td><td><?php echo $bibtex['monat'];?></td></tr>	
<tr><td class="bibtex">Tag:	</td><td><?php echo $bibtex['tag'];?></td></tr>	
<tr><td class="bibtex">Nummer:	</td><td><?php echo $bibtex['nummer'];?></td></tr>	
<tr><td class="bibtex">Seiten:	</td><td><?php echo $bibtex['seiten'];?></td></tr>		
<tr><td class="bibtex">Umfang:	</td><td><?php echo $bibtex['umfang'];?></td></tr>	
<tr><td class="bibtex">Reihe:	</td><td><?php echo $bibtex['reihe'];?></td></tr>	
<tr><td class="bibtex">Anmerkung:	</td><td><?php echo $bibtex['anmerkung'];?></td></tr>	
<tr><td class="bibtex">ISBN:	</td><td><?php echo $bibtex['isbn'];?></td></tr>	
<tr><td class="bibtex">ISSN:	</td><td><?php echo $bibtex['issn'];?></td></tr>	
<tr><td class="bibtex">DOI:	</td><td><?php echo $bibtex['doi'];?></td></tr>	
<tr><td class="bibtex">URL:	</td><td><?php echo $bibtex['url'];?></td></tr>	
<tr><td class="bibtex">URN:	</td><td><?php echo $bibtex['urn'];?></td></tr>	
<tr><td class="bibtex">WP	</td><td><?php echo $bibtex['wp'];?></td></tr>	
<tr><td class="bibtex">inLit:	</td><td><?php echo $bibtex['inlit'];?></td></tr>		
<tr><td class="bibtex">inFN:	</td><td><?php echo $bibtex['infn'];?></td></tr>	
<tr><td class="bibtex">Schlüssel:	</td><td><?php echo $bibtex['schluessel'];?></td></tr>	
<?php endif ?>
</table>

<p>
<div class="document-page diff clearfix">
  <div class="src-wrapper">
    <h4><?php echo $this->translate("Fragments"); ?></h4>
	<?php $fragments = $document->getFragments(); ?>
	
	<?php foreach($fragments as $fragment):
		$content = $fragment->getContent('list', true);
		$source_bib = $fragment->getSource()->getLineFrom()->getPage()->getDocument()->getBibtex();
		//var_dump($plag_bib);
	?>
	<?php	if($source_bib['titel'] == $bibtex['titel']):	?>
	
	
	<div class="src-wrapper">
    <h4><?php echo $this->translate("Plag: "); echo $document->getTitle()?></h4>
    <p>From: page <?php echo $fragment->getPlag()->getLineFrom()->getPage()->getPageNumber(); ?>, line <?php echo $fragment->getPlag()->getLineFrom()->getLineNumber(); ?></p>
    <p>To: page <?php echo $fragment->getPlag()->getLineTo()->getPage()->getPageNumber(); ?>, line <?php echo $fragment->getPlag()->getLineTo()->getLineNumber(); ?></p>    
    <div id="candidateText"><?php echo $content['plag']; ?></div>
  </div>
  <div class="src-wrapper">
    <h4><?php echo $this->translate("Source: "); echo $fragment->getSource()->getLineFrom()->getPage()->getDocument()->getTitle();?></h4>
    <p>From: page <?php echo $fragment->getSource()->getLineFrom()->getPage()->getPageNumber(); ?>, line <?php echo $fragment->getSource()->getLineFrom()->getLineNumber(); ?></p>
    <p>To: page <?php echo $fragment->getSource()->getLineTo()->getPage()->getPageNumber(); ?>, line <?php echo $fragment->getSource()->getLineTo()->getLineNumber(); ?></p>
    <div id="sourceText"><?php echo $content['source']; ?></div>
  </div>
	<?php endif ?>
  <?php endforeach ?>
</div>
</p>


</div>
