
<?php if ($this->pageCount): ?>
<ul class="pagination">
<li><a class="numbers"><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> <?php echo $this->translate("of"); ?> <?php echo $this->totalItemCount; ?> &nbsp;</a></li>
 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <li>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">|«</a>
  </li>
<?php else: ?>
  <li><a class="disabled">|«</a></li>
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li>  
<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">«</a>
</li>
  <?php else: ?>
  <li><a class="disabled">«</a></li>
<?php endif; ?>
 
 <!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li>
    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
        </li>
  <?php else: ?>
    <li><a class="active"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">»</a>
  </li>
<?php else: ?>
  <li>
  <a class="disabled">»</a>
  </li>
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <li>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">»|</a>
  </li>
<?php else: ?>
  <li><a class="disabled">»|</a></li>
<?php endif; ?>
 
</ul><br style="clear: both" />
<?php endif; ?>