<?php
$this->title = $this->translate("De-hyphenator");
$this->headTitle($this->title);
?>
Document: <?php echo $this->page->getDocument()->getTitle(); ?><br />
Page: <?php echo $this->page->getPageNumber(); ?><br />
<div class="document-page">
<?php

foreach($this->pageLines as $pageLine) {
  if($pageLine["hasHyphen"]) {
    echo "<div class=\"page-line highlight\"><div class=\"checkbox-column\"><input checked=\"checked\" type=\"checkbox\" /></div>" . $pageLine["content"] . "</div>";
  } else {
    echo "<div class=\"page-line\"><div class=\"checkbox-column\">&nbsp;</div>" . $pageLine["content"] . "</div>";
  }
}
?>
</div>
