<?php $this->headTitle($this->title); ?>
<h3><?php echo $this->subtitle; ?> <small>Fragment</small></h3>

<div class="document-page diff clearfix show-contextmenu">
  <div id="candidate-page" class="src-wrapper">
    <?php echo $this->pageContent; ?>

    <?php echo $this->partial('partials/next-prev-paginator.phtml', array('prevLink'=>$this->prevPageLink, 'nextLink'=>$this->nextPageLink)); ?>
  </div>

  <select name="source-document">
    <option>test</option>
  </select>
  <div id="source-page" class="src-wrapper">
    <?php if(isset($this->source)): ?>
      <?php echo $this->sourceContent; ?>
      <?php echo $this->partial('partials/next-prev-paginator.phtml', array('prevLink'=>$this->prevSourcePageLink, 'nextLink'=>$this->nextSourcePageLink)); ?>
    <?php endif; ?>
  </div>
</div>

<?php // @todo: think about a better way to open a new page with post data in jquery ?>
<form method="post" action="/document_fragment/create" id="fragment-create">
  <input type="hidden" name="candidatePage" value="<?php echo $this->page->getId(); ?>" id="fragment-candidate-page" />
  <input type="hidden" name="candidateStartLine" id="fragment-candidate-start-line" />
  <input type="hidden" name="candidateEndLine" id="fragment-candidate-end-line" />
  <?php if(isset($this->source)): ?>
    <input type="hidden" name="sourcePage"  value="<?php echo $this->source->getId(); ?>" id="fragment-source-page" />
    <input type="hidden" name="sourceStartLine" id="fragment-source-start-line" />
    <input type="hidden" name="sourceEndLine" id="fragment-source-end-line" />
  <?php endif; ?>
</form>
