<?php
    $this->title = $this->translate("List of document pages");
    $this->headTitle($this->title);
?>
<table cellpadding="0" cellspacing="0" class="default"> 
  <tr>
    <th><?php echo $this->translate("Page number"); ?></th>
    <th style="width: 100px;"><?php echo $this->translate("Actions"); ?></th>
  </tr>
  <?php 
  $i = 0;
  foreach($this->listPages as $page): 
    ?>
  <tr <?php echo ($i++ %2 == 0) ? "class=\"even\"" : ""; ?>>
    <td><a href="/document_page/show/id/<?php echo $page->getId(); ?>"><?php echo $page->getPageNumber(); ?></a></td>
    <td><a href="<?php echo "/document_page/edit/id/" . $page->getId(); ?>"><img class="icon" src="/resources/icons/page_edit.png" title="<?php echo $this->translate("edit"); ?>" /></a></td>
  </tr>
  <?php endforeach; ?>
</table>