<?php $this->headTitle($this->title); ?>
<h3><?php echo $this->translate("Pages overview"); ?></h3>

<div class="default-container">
<div class="document-page-overview">
  <?php $i = 0; ?>
  <?php foreach($this->paginator as $page): ?>
  <div class="page percentage-<?php echo $page->getPlagiarismPercentage(); ?>">
    <a href="/document_page/show/id/<?php echo $page->getId(); ?>"><?php echo Unplagged_Helper::formatDocumentPageNumber($page->getPageNumber()); ?></a>
  </div>
  <?php endforeach; ?>
</div>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>