<?php
$this->title = $this->translate("Page details");
$this->headTitle($this->title);
?>
Document: <?php echo $this->page->getDocument()->getTitle(); ?><br />
Page number: <?php echo $this->page->getPageNumber(); ?><br />

Content: <br />
<div class="document-page">
  <?php 
  $lines = explode('<br />', $this->page->getContent());
  
  ?>
  <ol>
  <?php foreach($lines as $line): ?>
    <li><?php echo $line; ?></li>
  <?php endforeach; ?>
</ol>
  
  <?php /*
  <tr <?php echo ($i++ %2 == 0) ? "class=\"even\"" : ""; ?>>
    <td><a href="/document_page/show/id/<?php echo $page->getId(); ?>"><?php echo $page->getPlagiarismPercentage() . " "; echo Unplagged_Helper::formatDocumentPageNumber($page->getPageNumber()); ?></a></td>
    <td>
          <a href="<?php echo "/document_page/de-hyphen/id/" . $page->getId(); ?>"><img class="icon" src="<?php echo $this->baseUrl('images/icons/text_padding_right.png'); ?>" title="<?php echo $this->translate("de-hyphen"); ?>" /></a>
  <a href="<?php echo "/document_page/stopwords/id/" . $page->getId(); ?>"><img class="icon" src="<?php echo $this->baseUrl('images/icons/zoom.png'); ?>" title="<?php echo $this->translate("stopword"); ?>" /></a>
  <a href="<?php echo "/document_page/detection-reports/id/" . $page->getId(); ?>"><img class="icon" src="<?php echo $this->baseUrl('images/icons/report_magnify.png'); ?>" title="<?php echo $this->translate("Plagiarism Detection Reports"); ?>" /></a>
  <a href="<?php echo "/document_page/edit/id/" . $page->getId(); ?>"><img class="icon" src="<?php echo $this->baseUrl('images/icons/pencil.png'); ?>" title="<?php echo $this->translate("edit"); ?>" /></a>
    <a href="<?php echo "/document_page/delete/id/" . $page->getId(); ?>"><img class="icon" src="<?php echo $this->baseUrl('images/icons/delete.png'); ?>" title="<?php echo $this->translate("delete"); ?>" /></a>
    </td>
  </tr>*/
  ?>
</div>
