<?php
$this->title = $this->translate("Page details");
$this->headTitle($this->title);
?>
Document: <?php echo $this->page->getDocument()->getTitle(); ?><br />
Page number: <?php echo $this->page->getPageNumber(); ?><br />

Content: <br />
<div class="document-page">
  <?php 
  $lines = explode('<br />', $this->page->getContent());
  
  ?>
  <ol>
  <?php foreach($lines as $line): ?>
    <li><?php echo $line; ?></li>
  <?php endforeach; ?>
</ol>
</div>
