<?php $this->headTitle($this->title); ?>
<h3><?php echo vprintf($this->translate($this->subtitle[0]), $this->subtitle[1]); ?> <small><?php echo $this->translate("Stopwords highlighting"); ?></small></h3>

<div class="document-page src-wrapper"><?php echo $this->stopWordContent; ?></div>

<?php echo $this->partial('partials/next-prev-paginator.phtml', array('prevLink'=>$this->prevPageLink, 'nextLink'=>$this->nextPageLink)); ?>
