<?php
/*
 * Unplagged - The plagiarism detection cockpit.
 * Copyright (C) 2012 Unplagged
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<div class="span7">
<h1><?php echo $this->translate('Credits'); ?></h1>
<h2><?php echo $this->translate('Resources'); ?></h2>
<p><?php echo $this->translate('We are very grateful for all the great free software and resources that make Unplagged possible. We especially would like to thank:'); ?></p>
<ul>
  <li><?php echo sprintf($this->translate('%sSilk Icons%s created by Mark James'), '<a href="http://www.famfamfam.com/lab/icons/silk/">', '</a>'); ?></li>
  <li><a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a></li>
  <li><a href="http://www.doctrine-project.org/">Doctrine</a></li>
  <li><a href="http://framework.zend.com/">Zend Framework 2</a></li>
  <li><a href="http://sass-lang.com/">Sass</a> <?php echo $this->translate('and'); ?> <a href="http://compass-style.org/">Compass</a></li>
</ul>
</div>