<nav id="actions-menu" class="well poped-in">
  <ul class="nav nav-list">
    <li class="nav-header">
      Actions
    </li>
    <li>
      <a href="<?php echo "/document_page/list/id/" . $this->documentId; ?>">
        <i class="icon-page icon-fam"></i><span><?php echo $this->translate("Show"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document/edit/id/" . $this->documentId; ?>">
        <i class="icon-pencil icon-fam"></i><span><?php echo $this->translate("Edit"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document/delete/id/" . $this->documentId; ?>">
        <i class="icon-delete icon-fam"></i><span><?php echo $this->translate("Remove"); ?></span>
      </a>
    </li>
        <li>
      <a href="<?php echo "/document_page/create/document/" . $this->documentId; ?>">
        <i class="icon-page-add icon-fam"></i><span><?php echo $this->translate("Add page"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document/detect-plagiarism/id/" . $this->documentId; ?>">
        <i class="icon-eye icon-fam"></i><span><?php echo $this->translate("Detect Plagiarism"); ?></span>
      </a>
    </li>
  </ul>
</nav>