<nav id="actions-menu" class="well fixed-nav poped-in">
  <h5>Actions Menu</h5>
  <ul class="nav nav-list">
    <li class="nav-header">Actions</li>
    <li>
      <a href="<?php echo "/document_page/show/id/" . $this->pageId; ?>">
        <i class="icon-page icon-fam"></i><span><?php echo $this->translate("Show"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/edit/id/" . $this->pageId; ?>">
        <i class="icon-pencil icon-fam"></i><span><?php echo $this->translate("Edit"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/delete/id/" . $this->pageId; ?>">
        <i class="icon-delete icon-fam"></i><span><?php echo $this->translate("Remove"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/de-hyphen/id/" . $this->pageId; ?>">
        <i class="icon-text-padding-right icon-fam"></i><span><?php echo $this->translate("De-hyphen"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/stopwords/id/" . $this->pageId; ?>">
        <i class="icon-zoom icon-fam"></i><span><?php echo $this->translate("Non-stopword identification"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/simtext/id/" . $this->pageId; ?>">
        <i class="icon-table-row-delete icon-fam"></i><span><?php echo $this->translate("Simtext"); ?></span>
      </a>
    </li>
    <li class="nav-header">Links</li>
    <li>
      <a href="<?php echo "/document_fragment/list/page/" . $this->pageId; ?>">
        <i class="icon-textfield-rename icon-fam"></i><span><?php echo $this->translate("Fragments"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/detection-reports/id/" . $this->pageId; ?>">
        <i class="icon-report-magnify icon-fam"></i><span><?php echo $this->translate("Plagiarism Detection Reports"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/simtext-reports/id/" . $this->pageId; ?>">
        <i class="icon-table-row-delete icon-fam"></i><span><?php echo $this->translate("Simtext Reports"); ?></span>
      </a>
    </li>
    <li>
      <a href="<?php echo "/document_page/changelog/id/" . $this->pageId; ?>">
        <i class="icon-table-relationship icon-fam"></i><span><?php echo $this->translate("Changelog"); ?></span>
      </a>
    </li>
  </ul>
</nav>