<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->translate('Unplagged Installation Wizard'); ?></title>
    <?php echo $this->headLink()->appendStylesheet($this->basePath('style/install.css')); ?>
    <!-- Modernizr needs to stay in the head to work properly -->
    <script src="<?php echo $this->basePath('js/libs/modernizr-2.5.3.min.js'); ?>"></script>
  </head>
  <body>
    <?php echo $this->content; ?>
    <script src="<?php echo $this->basePath('js/libs/jquery-1.7.2.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/libs/bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/libs/jqBootstrapValidation.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/install.js'); ?>"></script>
  </body>
</html>

