<?php

return array(
    'router'=>array(
        'routes'=>array(
            'admin'=>array(
                'type'=>'Zend\Mvc\Router\Http\Literal',
                'options'=>array(
                    'route'=>'/installer/installAdmin',
                    'defaults'=>array(
                        'controller'=>'unpinstaller',
                        'action'=>'installAdmin',
                    ),
                ),
            ),
            'settings'=>array(
                'type'=>'Zend\Mvc\Router\Http\Literal',
                'options'=>array(
                    'route'=>'/installer/installSettings',
                    'defaults'=>array(
                        'controller'=>'unpinstaller',
                        'action'=>'installSettings',
                    ),
                ),
            ),
            'database'=>array(
                'type'=>'Zend\Mvc\Router\Http\Literal',
                'options'=>array(
                    'route'=>'/installer/installDatabase',
                    'defaults'=>array(
                        'controller'=>'unpinstaller',
                        'action'=>'installDatabase',
                    ),
                ),
            ),
            'directories'=>array(
                'type'=>'Zend\Mvc\Router\Http\Literal',
                'options'=>array(
                    'route'=>'/installer/installDirectories',
                    'defaults'=>array(
                        'controller'=>'unpinstaller',
                        'action'=>'installDirectories',
                    ),
                ),
            ),
            'installer'=>array(
                'type'=>'Zend\Mvc\Router\Http\Literal',
                'options'=>array(
                    'route'=>'/installer',
                    'defaults'=>array(
                        'controller'=>'unpinstaller',
                        'action'=>'index',
                    ),
                ),
            ),
        ),
    ),
    'console'=>array(
        'router'=>array(
            'routes'=>array(
                'update-db-schema'=>array(
                    'options'=>array(
                        'route'=>'--update-db-schema',
                        'defaults'=>array(
                            'controller'=>'unpconsoleinstaller',
                            'action'=>'updateDatabaseSchema',
                        ),
                    ),
                ),
                'delete-db-schema'=>array(
                    'options'=>array(
                        'route'=>'--delete-db-schema',
                        'defaults'=>array(
                            'controller'=>'unpconsoleinstaller',
                            'action'=>'deleteDatabaseSchema',
                        ),
                    ),
                ),
                'check-db-connection'=>array(
                    'options'=>array(
                        'route'=>'--check-db-connection',
                        'defaults'=>array(
                            'controller'=>'unpconsoleinstaller',
                            'action'=>'checkDatabaseConnection',
                        ),
                    ),
                ),
            ),
        ),
    ),
    'service_manager'=>array(
        'factories'=>array(
            'translator'=>'Zend\I18n\Translator\TranslatorServiceFactory',
        ),
    ),
    'translator'=>array(
        'locale'=>'en_EN',
        'fallbackLocale'=>'en_US',
        'translation_file_patterns'=>array(
            array(
                'type'=>'gettext',
                'base_dir'=>__DIR__ . '/../languages',
                'pattern'=>'%s.mo',
            ),
        ),
    ),
    'controllers'=>array(
        'invokables'=>array(
            'unpinstaller'=>'UnpInstaller\Controller\InstallerController',
            'unpconsoleinstaller'=>'UnpInstaller\Controller\ConsoleInstallerController',
        ),
    ),
    'view_manager'=>array(
        'display_not_found_reason'=>true,
        'display_exceptions'=>true,
        'doctype'=>'HTML5',
        'not_found_template'=>'error/404',
        'exception_template'=>'error/index',
        'template_map'=>array(
            'layout/installer'=>__DIR__ . '/../view/layout/layout.phtml',
            'installer/index'=>__DIR__ . '/../view/unpinstaller/installer/index.phtml',
        ),
        'template_path_stack'=>array(
            'unpinstaller'=>__DIR__ . '/../view',
        )
    )
);
