<?php
$defaultNamespace = new Zend_Session_Namespace('Default');
$layout = $this->layout();
?>
<?php echo $this->partial('partials/header.phtml', array('defaultNamespace'=>$defaultNamespace)); ?>
<div role="main" id="content" class="clearfix layout-2-columns-equal">
  <?php echo $this->partial('partials/messages.phtml', array('defaultNamespace'=>$defaultNamespace, 'flashMessages'=>$this->flashMessages)); ?>
  <h2><?php echo $this->escape($this->title); ?></h2>
  <div class="first left">
    <div id="main">
      <?php echo $layout->firstContent; ?>
    </div>
  </div>
  <div class="second right">
    <?php echo $layout->secondContent; ?>
  </div>
</div>
<?php echo $this->partial('partials/footer.phtml'); ?>