<?php
$defaultNamespace = new Zend_Session_Namespace('Default');
$em = Zend_Registry::getInstance()->entitymanager;
if($defaultNamespace->userId){
  $me = $em->getRepository('Application_Model_User')->findOneById($defaultNamespace->userId);
}else{
  $me = null;
}

// had to remove function because it somehow was included twice here
$qb = $em->createQueryBuilder();
$qb->add('select', "c.id AS value, c.alias AS label")
    ->add('from', 'Application_Model_Case c');

$dbresults = $qb->getQuery()->getResult();
$results = array();

foreach($dbresults as $key=>$value){
  $results[] = $value;
}
 
$cases = $results;

?>
<?php echo $this->partial('partials/header.phtml', array('defaultNamespace'=>$defaultNamespace, 'me'=>$me, 'cases'=>$cases)); ?>
<div role="main" class="clearfix">
  <?php echo $this->partial('partials/messages.phtml', array('defaultNamespace'=>$defaultNamespace, 'flashMessages'=>$this->flashMessages)); ?>
  <h2><?php echo $this->escape($this->title); ?></h2>
  <div class="main">
  <div id="main-wrapper">
    <div id="main">
      <?php
      // content from each view, the rest of this page is global to all views
      echo $this->layout()->content;
      ?>
    </div>
  </div>
  </div>
  <nav id="right-nav">
    <h4>Aktuelles und Kontroverses</h4>
    <ul>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
    </ul>
    <br />
    <h4>Berichte und Mitteilungen</h4>
    <ul>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
    </ul>
  </nav>
</div>

<?php echo $this->partial('partials/footer.phtml'); ?>
</body>
</html>