<?php
$defaultNamespace = new Zend_Session_Namespace('Default');
$em = Zend_Registry::getInstance()->entitymanager;
if($defaultNamespace->userId){
  $me = $em->getRepository('Application_Model_User')->findOneById($defaultNamespace->userId);
}else{
  $me = null;
}

/**
 *@todo this should only be temporary to tryout a different ui style  
 */
function findCases($em){
    
  $qb = $em->createQueryBuilder();
  $qb->add('select', "c.id AS value, c.alias AS label")
      ->add('from', 'Application_Model_Case c');

  $dbresults = $qb->getQuery()->getResult();
  $results = array();
  
  foreach($dbresults as $key=>$value){
    $results[] = $value;
  }
  
  return $results;
}

$cases = findCases($em);

?>
<?php echo $this->partial('partials/header.phtml', array('defaultNamespace'=>$defaultNamespace, 'me'=>$me, 'cases'=>$cases)); ?>
<div role="main" id="content" class="clearfix">

  <div class="main">
  <div id="main-wrapper">
    <div id="main">
      <?php
      if(!empty($this->flashMessages)){
        echo '<div class="flash-messages">';
        //@todo maybe switch to ul?
        foreach($this->flashMessages as $key=>$value){
          echo $this->translate($value) . "<br />";
        }
        echo '</div>';
      }
      ?>
      <h2><?php echo $this->escape($this->title); ?></h2>
      <?php

      // content from each view, the rest of this page is global to all views
      echo $this->layout()->content;
      ?>
    </div>
  </div>
  </div>
  <nav id="right-nav">
    <h4>Aktuelles und Kontroverses</h4>
    <ul>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
    </ul>
    <br />
    <h4>Berichte und Mitteilungen</h4>
    <ul>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
      <li><a href="#">News 1<span class="count">3</span></a></li>
    </ul>
  </nav>
</div>

<?php echo $this->partial('partials/footer.phtml'); ?>
</body>
</html>