<table cellpadding="0" cellspacing="0" class="default">
  <thead>
    <tr>
      <th style="width: 20px;"></th>
      <th><?php echo $this->translate("Filename"); ?></th>
      <th style="width: 110px;"><?php echo $this->translate("Uploaded"); ?></th>
      <th class="fit-content"><?php echo $this->translate("Actions"); ?></th>
    </tr>
  </thead>
  <tbody>
    <?php if(count($this->paginator)): ?>
      <?php foreach($this->paginator as $file): ?>
        <tr>
          <td data-label="<?php echo $this->translate("Icon"); ?>"><img class="icon" src="<?php echo $this->baseUrl('images/icons/' . Unplagged_Helper::getFileIconByExtension($file->getExtension())); ?>" /></td>
          <td data-label="<?php echo $this->translate("Filename"); ?>"><a <?php echo $file->isImage() ? 'class="picture"' : ""; ?> href="<?php echo $this->baseUrl('/image/show/id/' . $file->getId()); ?>"><?php echo $file->getFilename(); ?></a></td>
          <td data-label="<?php echo $this->translate("Uploaded"); ?>"><?php echo $file->getCreated()->format('Y-m-d'); ?></td>
          <td data-label="<?php echo $this->translate("Actions"); ?>" class="fit-content"><?php echo $this->partial('partials/action-dropdown.phtml', array('actions'=>$file->actions)); ?></td>
        </tr>
      <?php endforeach; ?>
    <?php else: ?>
      <tr>
        <td colspan="4" class="no-label"><?php echo $this->translate("No files found."); ?></td>
      </tr>
    <?php endif; ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>

<a class="btn btn-primary" href="<?php echo $this->uploadLink; ?>"><i class="icon-upload icon-fam"></i><?php echo $this->translate("Upload a file"); ?></a>

<div class="modal hide" id="parseFile">
  <form action="/file/parse" method="post">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><?php echo $this->translate('Create document'); ?></h3>
  </div>
  <div class="modal-body">
    <p><?php echo $this->translate('Please select the language of the text in the file, you want to create a document of.'); ?></p>
    <div class="form-horizontal">
        <fieldset>
          <div class="control-group">
            <label class="control-label" for="select01"><?php echo $this->translate('Language'); ?></label>
            <div class="controls">
              <input type="hidden" name="id" id="file-id" value="123"/>
              <select id="select01" name="language">
                <?php $languages = Zend_Registry::getInstance()->config->get('parser')->get('availableLanguages')->toArray(); ?>
                <?php foreach($languages as $language): ?>
                <option value="<?php echo $language; ?>"><?php echo $this->translate($language); ?></option>
                <?php endforeach; ?>
              </select>
            </div>
          </div>
        </fieldset>
      </div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal"><?php echo $this->translate('Abort'); ?></a>
    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Create document'); ?></button>
  </div>
  </form>
</div>