<?php
//$menu = $this->layout()->menu;

//$defaultNamespace = new Zend_Session_Namespace('Default');
//$me = Zend_Registry::getInstance()->user;

//$em = Zend_Registry::getInstance()->entitymanager;

//$query = $em->createQuery("SELECT c.id AS value, c.alias AS label FROM Application_Model_Case c WHERE :userId MEMBER OF c.collaborators");
//$query->setParameter('userId', $me->getId());
//$cases = $query->getArrayResult();
?>
<?php echo $this->partial('layout/header');//, array('defaultNamespace'=>$defaultNamespace, 'me'=>$me, 'cases'=>$cases)); ?>
<div role="main" class="clearfix">
  <?php echo $this->partial('layout/messages', array('defaultNamespace'=>$defaultNamespace, 'flashMessages'=>$this->flashMessages)); ?>
  <!--<div class="breadcrumbs">
  <?php //echo $this->navigation()->breadcrumbs(); ?>
  </div>-->
  <?php if(!empty($this->title)): ?>
  <h2><?php echo $this->escape($this->title); ?></h2>
  <?php endif; ?>
  <div class="main">
    <div id="main-wrapper">
      <div>
        <?php
        // content from each view, the rest of this page is global to all views
        echo $this->layout()->content;
        ?>
      </div>
    </div>
  </div>
</div>
<?php
if(!empty($menu)){
  echo $this->partial('layout/sidebar_menu', array('actions'=>$this->layout()->menu));
}
?>
<?php echo $this->partial('layout/footer'); ?>