<?php
//$menu = $this->layout()->menu;
//$query = $em->createQuery("SELECT c.id AS value, c.alias AS label FROM Application_Model_Case c WHERE :userId MEMBER OF c.collaborators");
//$query->setParameter('userId', $me->getId());
//$cases = $query->getArrayResult();
?>
<?php echo $this->partial('layout/header'); ?>
<div role="main" class="clearfix row-fluid">
  <?php echo $this->flashMessages(); ?>
  <?php echo $this->content; ?>
</div>
<?php if(!empty($menu)): ?>
  <aside>
    <?php //echo $this->render('layout/sidebar_menu', array('actions'=>$this->layout()->menu)); ?>
  </aside>
<?php endif; ?>
<?php echo $this->partial('layout/footer'); ?>