<?php
$this->headTitle($this->title);
?>
<table cellpadding="0" cellspacing="0" class="default"> 
  <thead>
    <tr>
      <th><?php echo $this->translate("Title"); ?></th>
      <th><?php echo $this->translate("Page"); ?></th>
      <th><?php echo $this->translate("Autor"); ?></th>
      <th><?php echo $this->translate("Ort"); ?></th>
      <th><?php echo $this->translate("Jahr"); ?></th>
      <th class="fit-content"><?php echo $this->translate("Actions"); ?></th>
    </tr>
  </thead>
  <tbody>
    <?php if(count($this->paginator)): ?>
      <?php foreach($this->paginator as $bibTex): ?>
        <tr>
          <td data-label="<?php echo $this->translate("Title"); ?>"><a href="/bibtex/show/id/<?php echo $bibTex->getId(); ?>"><?php echo $bibTex->getContent('title'); ?></a></td>
          <td data-label="<?php echo $this->translate("Pages"); ?>"><?php echo $bibTex->getContent('pages') ?></td>
          <td data-label="<?php echo $this->translate("Autor"); ?>"><?php echo $bibTex->getContent('author'); ?></td>
          <td data-label="<?php echo $this->translate("Ort"); ?>"><?php echo $bibTex->getContent('address'); ?></td>
          <td data-label="<?php echo $this->translate("Jahr"); ?>"><?php echo $bibTex->getContent('year'); ?></td>
          <td data-label="<?php echo $this->translate("Actions"); ?>" class="fit-content">
            <?php echo $this->partial('partials/action-dropdown.phtml', array('actions'=>$bibTex->actions)); ?>
          </td>
        </tr>
      <?php endforeach; ?>
    <?php else: ?>
      <tr>
        <td colspan="4" class="no-label"><?php echo $this->translate("No documents found."); ?></td>
      </tr>
    <?php endif; ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>