<footer role="contentinfo">
  <?php
  $partial = array('partial/footerMenu.phtml', 'unp-application');
  $this->navigation()->menu()->setPartial($partial);
  echo $this->navigation()->menu('footer_navigation')->setMaxDepth(0);
  ?>
</footer>
</div>    
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="<?php echo $this->basePath('js/libs/jquery-1.7.2.min.js'); ?>"><\/script>')</script>
<?php
//plugins from other vendors should be put here
//@todo add automatic minification of scripts later on
?>
<script defer src="<?php echo $this->basePath('js/libs/jquery-ui-1.8.17.custom.min.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/numberfy.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/jquery.lightbox-0.5.min.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/bootstrap.min.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/chosen.jquery.min.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/jquery.ba-hashchange.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/plupload/js/plupload.full.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/plupload/js/jquery.plupload.queue/jquery.plupload.queue.js'); ?>"></script>
<script defer src="<?php echo $this->basePath('js/libs/i18next-1.3.3.min.js'); ?>"></script>
<?php //Language files for plupload ?>
<?php $localeString = substr($this->getHelperPluginManager()->get('translate')->getTranslator()->getLocale(), 0, 2); ?>
<?php $pluploadTranslationPath = 'js/libs/plupload/js/i18n/' . $localeString . '.js'; ?>
<?php if(is_readable(BASE_PATH . DIRECTORY_SEPARATOR . 'public' . $pluploadTranslationPath)): ?>
  <script defer src="<?php echo $this->basePath($pluploadTranslationPath); ?>"></script>
<?php endif; ?>
<script>
  $(document).ready(function(){ 
    $.i18n.init({
      lng: '<?php echo $localeString; ?>', 
      fallbackLng: 'en', 
      resGetPath: '/js/i18n/__lng__.json', 
      debug: false,
      getAsync: false
    });
  });
</script>
<?php //own plugins go here ?>
<script defer src="<?php echo $this->basePath('js/plugins.js'); ?>"></script>
<?php //all other small scripts can be put here ?>
<script defer src="<?php echo $this->basePath('js/script.js'); ?>"></script>
</body>
</html>