<!doctype html>
<!--[if lte IE 7]> <html class="no-js ie7 oldie"> <![endif]-->
<!--[if IE 8]> <html class="no-js ie8 oldie"> <![endif]-->
<!--[if IE 9]> <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
    <!-- Design based on http://www.premiumpixels.com/ -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->appendStylesheet($this->basePath('style/styles.css')); ?>
    <!-- Modernizr needs to stay in the head to work properly, every other script should go in the bottom. -->
    <script src="<?php echo $this->basePath('js/libs/modernizr-2.5.3.min.js'); ?>"></script>
  </head>
  <body>
    <?php echo $this->partial('layout/noscript'); ?>
    <?php echo $this->partial('layout/chrome-frame'); ?>
    <header class="navbar navbar-inverse" role="toolbar">
      <div class="navbar-inner">
        <div class="container content">
          <?php
          $this->navigation()->menu()->setUlClass('nav');
          $this->navigation()->menu()->escapeLabels(false);
          echo $this->navigation()->menu('main_navigation')->setMaxDepth(0);
          ?>
          <?php if($this->zfcUserIdentity()): ?>
            <li class="dropdown">
              <a href="<?php echo $this->basePath('user/edit'); ?>" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-user icon-white"></i> <?php echo $this->zfcUserIdentity()->getUsername(); ?> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu user-dropdown">
                <li>
                  <a href="<?php echo $this->basePath('user/edit'); ?>"><?php echo $this->translate('Edit Profile'); ?></a>
                </li>
                <li>
                  <a href="<?php echo $this->basePath('user/files'); ?>"><?php echo $this->translate('My Files'); ?></a>
                </li>
                <li>
                  <a href="<?php echo $this->basePath('auth/logout'); ?>"><?php echo $this->translate('Logout'); ?></a>
                </li>
                <li class="avatar-wrap">
                  <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array(), array('class'=>'avatar')); ?>
                </li>
              </ul>
            </li>
          <?php else: ?>
            <div class="dropdown login-group btn-group pull-left">
              <a id="login-button" class="btn dropdown-toggle" 
                 title="<?php echo $this->translate('Login'); ?>" 
                 href="<?php echo $this->basePath('user/login'); ?>"><?php echo $this->translate('Login'); ?>
                <span class="caret"></span>
              </a>
              <div class="dropdown-menu login-dropdown">
                <?php echo $this->zfcUserLoginWidget(); ?>
              </div>
            </div>
          <?php endif; ?>
          <form class="form-search pull-right">
            <div class="input-append">
              <input type="text" 
                     class="span3 search-query" 
                     placeholder="<?php echo $this->translate('Search'); ?>" type="search" />
              <button type="submit" class="btn"><i class="icon-search"></i></button>
          </form>
        </div>
      </div>
    </header>
    <div class="pagewrap">
      <header role="banner" class="clearfix">
        <h1 class="ir"><?php $this->translate('Unplagged - The Plagiarism Detection Workbench'); ?></h1>
        <?php $this->navigation()->menu()->setPartial(null); ?>
        <?php $this->navigation()->menu()->setULClass('navigation'); ?>
        <nav><?php echo $this->navigation()->menu('navigation'); ?></nav>
        <div class="case-settings-box clearfix">
          <?php
          /* $currentLabel = '';
            $currentValue = null;
            if($this->me->getCurrentCase() instanceof Application_Model_Case){
            $currentLabel = $this->me->getCurrentCase()->getPublishableName();
            $currentValue = $this->me->getCurrentCase()->getId();
            } */
          ?>
          <form class="current-case form-inline" method="POST" action="<?php echo $this->basePath('user/set-current-case'); ?>">
            <select data-placeholder="<?php echo $this->translate('Select a Case'); ?>" name="case">
              <option></option>
              <?php if(count($this->cases) > 0): ?>
                <?php foreach($this->cases as $case): ?>
                  <option <?php //if($case['value'] == $currentValue) echo 'selected';       ?> 
                    value="<?php echo $case['value']; ?>">
                      <?php echo $case['label']; ?>
                  </option>
                <?php endforeach; ?>
              <?php endif; ?>
            </select>
            <button class="button"><?php echo $this->translate('Ok'); ?></button>  
          </form>
        </div>
      </header>