<!doctype html>
<!--[if lte IE 7]> <html class="no-js ie7 oldie"> <![endif]-->
<!--[if IE 8]> <html class="no-js ie8 oldie"> <![endif]-->
<!--[if IE 9]> <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
    <!-- Design based on http://www.premiumpixels.com/ -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->appendStylesheet($this->basePath('style/styles.css')); ?>
    <!-- Modernizr needs to stay in the head to work properly, every other script should go in the bottom. -->
    <script src="<?php echo $this->basePath('js/libs/modernizr-2.5.3.min.js'); ?>"></script>
  </head>
  <body>
    <?php echo $this->partial('layout/noscript'); ?>
    <?php echo $this->partial('layout/chrome-frame'); ?>
    <header class="navbar navbar-inverse" role="toolbar">
      <div class="navbar-inner">
        <div class="container">
          <?php
          $this->navigation()->menu()->setUlClass('nav');
          $this->navigation()->menu()->escapeLabels(false);
          echo $this->navigation()->menu('navigation')->setMaxDepth(0);
          ?>
          <?php if($this->zfcUserIdentity()): ?>
            <div class="dropdown login-group btn-group pull-left">
              <a href="<?php echo $this->basePath('user/edit'); ?>" class="btn dropdown-toggle">
                <i class="icon-user"></i>
                <?php echo $this->zfcUserIdentity()->getUsername(); ?> 
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu user-dropdown">
                <li>
                  <a href="<?php echo $this->basePath('user/edit'); ?>"><?php echo $this->translate('Edit Profile'); ?></a>
                </li>
                <li>
                  <a href="<?php echo $this->basePath('user/files'); ?>"><?php echo $this->translate('My Files'); ?></a>
                </li>
                <li>
                  <a href="<?php echo $this->basePath('user/logout'); ?>"><?php echo $this->translate('Logout'); ?></a>
                </li>
                <li class="avatar-wrap">
                  <?php
                  $gravatarOptions = array('img_size'=>40);
                  $tagAttributes = array('class'=>'avatar', 'width'=>'40', 'height'=>'40');
                  echo $this->gravatar($this->zfcUserIdentity()->getEmail(), $gravatarOptions, $tagAttributes);
                  ?>
                </li>
              </ul>
            </div>
          <?php else: ?>
            <div class="dropdown login-group btn-group pull-left">
              <a id="login-button" class="btn dropdown-toggle" 
                 title="<?php echo $this->translate('Login'); ?>" 
                 href="<?php echo $this->basePath('user/login'); ?>"><?php echo $this->translate('Login'); ?>
                <span class="caret"></span>
              </a>
              <div class="dropdown-menu login-dropdown">
                <?php echo $this->zfcUserLoginWidget(); ?>
              </div>
            </div>
          <?php endif; ?>
          <!--<form class="form-search pull-right navbar-search">
            <input type="text" 
                   class="span3 search-query" 
                   placeholder="<?php echo $this->translate('Search'); ?>" type="search" />
          </form>-->
        </div>
      </div>
    </header>
    <div class="pagewrap">
      <header role="banner" class="clearfix">
        <img class="logo" src="<?php echo $this->basePath('/images/logo.png'); ?>" title="Unplagged <?php echo $this->translate('The Plagiarism Detection Workbench'); ?>" />
        <?php $this->navigation()->menu()->setPartial(null); ?>
        <?php $this->navigation()->menu()->setULClass('navigation'); ?>
        <nav><?php echo $this->navigation()->menu('main_navigation'); ?></nav>
        <div class="case-settings-box clearfix">
          <?php if($this->zfcUserIdentity()): ?>
          <?php echo $this->caseSelection($this->zfcUserIdentity()->getCurrentCase()); ?>
          <?php endif; ?>
          <a href="<?php echo $this->basePath('/case/create'); ?>" class="icon-fam fam-icon-add ir pul-right" title="<?php echo $this->translate('Add Case'); ?>"><?php echo $this->translate('Add Case'); ?></a>
        </div>
      </header>