<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_User extends \Application_Model_User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function updated()
    {
        $this->__load();
        return parent::updated();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function getVerificationHash()
    {
        $this->__load();
        return parent::getVerificationHash();
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getCurrentCase()
    {
        $this->__load();
        return parent::getCurrentCase();
    }

    public function setCurrentCase($currentCase)
    {
        $this->__load();
        return parent::setCurrentCase($currentCase);
    }

    public function unsetCurrentCase()
    {
        $this->__load();
        return parent::unsetCurrentCase();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function addFile(\Application_Model_File $file)
    {
        $this->__load();
        return parent::addFile($file);
    }

    public function removeFile(\Application_Model_File $file)
    {
        $this->__load();
        return parent::removeFile($file);
    }

    public function getFiles()
    {
        $this->__load();
        return parent::getFiles();
    }

    public function clearFiles()
    {
        $this->__load();
        return parent::clearFiles();
    }

    public function hasFiles()
    {
        $this->__load();
        return parent::hasFiles();
    }

    public function setVerificationHash($verificationHash)
    {
        $this->__load();
        return parent::setVerificationHash($verificationHash);
    }

    public function getAvatar()
    {
        $this->__load();
        return parent::getAvatar();
    }

    public function getDirectName()
    {
        $this->__load();
        return parent::getDirectName();
    }

    public function getDirectLink()
    {
        $this->__load();
        return parent::getDirectLink();
    }

    public function getIconClass()
    {
        $this->__load();
        return parent::getIconClass();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function created()
    {
        $this->__load();
        return parent::created();
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'created', 'comments', 'updated', 'username', 'password', 'email', 'firstname', 'lastname', 'verificationHash', 'salt', 'role', 'state', 'avatar', 'currentCase', 'files');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}