<?php
// some init stuff
$errors = $this->element->getMessages();
$disabled = $this->disabled || false;

$values = $this->element->getValue();
$defaultValues = $values['default'];
$inheritedValues = $values['inherited'];

$roleIds = array();
foreach($defaultValues as $permission => $valueRoleIds){
  foreach($valueRoleIds as $roleId) {
    $roleIds[$roleId][] = $permission;
  }
}

$defaultRoleIds = array();
foreach($inheritedValues as $permission => $valueRoleIds){
  foreach($valueRoleIds as $roleId) {
    $defaultRoleIds[$roleId][] = $permission;
  }
}
?>

<?php echo $this->formLabel($this->element->getName(), $this->element->getLabel()) ?>
<dd>
  <input id="<?php echo $this->element->getName() ?>" type="text" data-view-script="permission" data-callback="<?php echo $this->callback; ?>" />
  <?php
  if(!empty($errors)){
    echo $this->formErrors($errors);
  }

  if($this->element->getDescription()){
    echo '<div class="hint">' . $this->element->getDescription() . '</div>';
  }
  ?>
  <div class="permissions-wrapper" data-wrapper-for="<?php echo $this->element->getName(); ?>">
    <?php if($defaultValues){ ?>
      <?php foreach($roleIds as $roleId => $rolePermissions): ?>
        <?php $user = Zend_Registry::getInstance()->entitymanager->getRepository('Application_Model_User')->findOneByRole($roleId); ?>
        <div class="well" data-source="<?php echo $this->element->getName(); ?>" data-id="<?php echo $roleId; ?>">
          <img class="avatar no-shadow" src="<?php echo $user->getAvatar(); ?>">
          <div class="names">
            <span class="username"><?php echo $user->getUsername(); ?></span>
          </div>
          <div class="options">
            <?php foreach($this->permissionActions as $permissionAction) { ?>
            <span id="<?php echo $permissionAction; ?>-<?php echo $roleId; ?>-label">
              <label for="<?php echo $permissionAction; ?>-<?php echo $roleId; ?>"><?php echo $this->translate($permissionAction); ?></label>
              <?php $checked = in_array($permissionAction, $rolePermissions) ? 'checked="checked"' : ''; ?>
              <?php $disabled = in_array($permissionAction, $defaultRoleIds[$roleId]) ? 'disabled' : ''; ?>
              <input <?php echo $checked; ?> type="checkbox" <?php if(empty($disabled)) { ?>name="<?php echo $permissionAction; ?>[]"<?php } ?> id="<?php echo $permissionAction; ?>-<?php echo $roleId; ?>" value="<?php echo $roleId; ?>" class="btn btn-checkbox btn-small <?php echo $disabled; ?>">
            </span>
            <?php } ?>
            <?php if(empty($defaultRoleIds[$roleId])): ?>
            <a href="#" class="btn btn-danger" data-remove="true" data-for="<?php echo $roleId; ?>"><i class="icon-remove"></i></a>
            <?php endif; ?>
          </div>
          <input type="hidden" name="<?php echo $this->element->getName(); ?>[]" value="<?php echo $roleId; ?>" />
        </div>
      <?php endforeach; ?>
    <?php } ?>
  </div>  
</dd>