<?php
/*
 * Unplagged - The plagiarism detection cockpit.
 * Copyright (C) 2012 Unplagged
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *  
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php echo $this->editForm; ?>
<!--<form action="" method="POST">
  <?php foreach($this->allPermissions as $controllerName=>$permissions): ?>
    <div class="well">
      <h3><?php echo $controllerName; ?></h3>
        <?php foreach($permissions as $permission): ?>
      <span class="test">
          <a type="checkbox" name="<?php echo $permission; ?>"type="button" class="btn" data-toggle="button" value="<?php echo $permission; ?>"><?php echo $permission; ?></a>
      </span>
        <?php endforeach; ?>
    </div>
  <?php endforeach; ?>
  <button class="btn btn-primary">Submit</button>
</form>-->