<?php
// some init stuff
$errors = $this->element->getMessages();
$disabled = $this->disabled || false;
?>

<?php echo $this->formLabel($this->element->getName(), $this->element->getLabel()) ?>
<dd>
  <input id="<?php echo $this->element->getName() ?>" type="text" data-view-script="collaborator" data-case="<?php echo $this->case ? $this->case->getId() : ''; ?>" data-callback="<?php echo $this->callback; ?>" />
  <?php
  if(!empty($errors)){
    echo $this->formErrors($errors);
  }

  if($this->element->getDescription()){
    echo '<div class="hint">' . $this->element->getDescription() . '</div>';
  }
  ?>
  <div class="collaborators-wrapper" data-wrapper-for="<?php echo $this->element->getName(); ?>">
    <?php if($this->element->getValue()){ ?>
      <?php foreach($this->element->getValue() as $roleId=>$inheritedRoleId): ?>
        <?php $role = Zend_Registry::getInstance()->entitymanager->getRepository('Application_Model_User_Role')->findOneById($roleId); ?>
        <?php if($role): ?>
          <div class="well" data-source="<?php echo $this->element->getName(); ?>" data-id="<?php echo $role->getUser()->getId(); ?>">
            <img class="avatar no-shadow" src="<?php echo $role->getUser()->getAvatar(); ?>" />
            <div class="names">
              <span class="username"><?php echo $role->getUser()->getUsername(); ?></span>
            </div>
            <div class="options">
              <select class="span2" name="<?php echo $this->element->getName(); ?>[<?php echo $role->getId(); ?>]" style="width: 150px;">
                <?php foreach($this->roles as $inheritedRole): ?>
                  <?php $selected = ($inheritedRoleId == $inheritedRole->getId()) ? 'selected="selected"' : ''; ?>
                  <option <?php echo $selected; ?> value="<?php echo $inheritedRole->getId(); ?>"><?php echo $inheritedRole->getRoleId(); ?></option>
                <?php endforeach; ?>
              </select>
              <input type="hidden" name="<?php echo $this->element->getName(); ?>-users[]" value="<?php echo $role->getUser()->getId(); ?>" />

              <a href="#" class="btn btn-danger" data-remove="true" data-for="<?php echo $role->getUser()->getId(); ?>"><i class="icon-remove"></i></a>
            </div>
            </div>
          <?php endif; ?>
        
      <?php endforeach; ?>
    <?php } ?>
  </div>  
</dd>