<?php
// some init stuff
$errors = $this->element->getMessages();
$disabled = $this->disabled || false;
?>

<?php echo $this->formLabel($this->element->getName(), $this->element->getLabel()) ?>
<dd>
  <input id="<?php echo $this->element->getName() ?>" type="text" data-view-script="user" data-callback="<?php echo $this->callback; ?>" />
  <?php
  if(!empty($errors)){
    echo $this->formErrors($errors);
  }

  if($this->element->getDescription()){
    echo '<div class="hint">' . $this->element->getDescription() . '</div>';
  }
  ?>
  <div class="collaborators-wrapper" data-wrapper-for="<?php echo $this->element->getName(); ?>">
    <?php if($this->element->getValue()){ ?>
      <?php foreach($this->element->getValue() as $userId): ?>
        <?php $user = Zend_Registry::getInstance()->entitymanager->getRepository('Application_Model_User')->findOneById($userId); ?>
        <div class="well" data-source="<?php echo $this->element->getName(); ?>" data-id="<?php echo $user->getId(); ?>">
          <img class="avatar no-shadow" src="<?php echo $user->getAvatar(); ?>" />
          <div class="names">
            <span class="username"><?php echo $user->getUsername(); ?></span>
          </div>
          <div class="options">
            <select class="span2" style="width: 150px;">
              <option>test</option>
            </select>
            <a href="#" class="btn btn-danger" data-remove="true" data-for="<?php echo $user->getId(); ?>"><i class="icon-remove"></i></a>
          </div>
          <input type="hidden" name="<?php echo $this->element->getName(); ?>[]" value="<?php echo $user->getId(); ?>" />
        </div>
      <?php endforeach; ?>
    <?php } ?>
  </div>  
</dd>