<?php
$this->title = $this->translate("List of cases");
$this->headTitle($this->title);
?>
<table cellpadding="0" cellspacing="0" class="default"> 
  <thead>
    <tr>
      <th><?php echo $this->translate("Name"); ?></th>
      <th style="width: 110px;"><?php echo $this->translate("Alias"); ?></th>
      <th style="width: 100px;"><?php echo $this->translate("Abbreviation"); ?></th>
      <th class="fit-content"><?php echo $this->translate("Actions"); ?></th>
    </tr>
  </thead>
  <tbody>
    <?php if(count($this->paginator)): ?>
      <?php foreach($this->paginator as $case): ?>
        <tr>
          <td data-label="<?php echo $this->translate("Name"); ?>"><?php echo $case->getName(); ?></td>
          <td data-label="<?php echo $this->translate("Alias"); ?>"><?php echo $case->getAlias(); ?></td>
          <td data-label="<?php echo $this->translate("Abbreviation"); ?>"><?php echo $case->getAbbreviation(); ?></td>
          <td data-label="<?php echo $this->translate("Actions"); ?>" class="fit-content"><?php echo $this->partial('partials/action-dropdown.phtml', array('actions'=>$case->actions)); ?></td>
        </tr>
      <?php endforeach; ?>
    <?php else: ?>
      <tr>
        <td colspan="4" class="no-label"><?php echo $this->translate("No cases found."); ?></td>
      </tr>
    <?php endif; ?>
  </tbody>
</table> 
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>

<a class="btn btn-primary" href="/case/create"><i class="icon-create-case icon-fam"></i><?php echo $this->translate("Create a new case"); ?></a>
