<?php
    $this->title = $this->translate("List of cases");
    $this->headTitle($this->title);
?>
<table cellpadding="0" cellspacing="0" class="default"> 
  <tr>
    <th><?php echo $this->translate("Name"); ?></th>
    <th style="width: 110px;"><?php echo $this->translate("Alias"); ?></th>
    <th style="width: 100px;"><?php echo $this->translate("Actions"); ?></th>
  </tr>
  <?php 
  $i = 0;
  foreach($this->listCases as $case): 
    ?>
  <tr <?php echo ($i++ %2 == 0) ? "class=\"even\"" : ""; ?>>
    <td><?php echo $case->getName(); ?></td>
    <td><?php echo $case->getAlias(); ?></td>
    <td></td>
  </tr>
  <?php endforeach; ?>
</table>
  <a href="/case/create"><?php echo $this->translate("Create a case"); ?></a>