<div class="btn-group">
  <button class="btn dropdown-toggle"><?php echo $this->translate('Action'); ?> <span class="caret"></span></button>
  <ul class="dropdown-menu pull-right">
    <?php foreach($this->actions as $action): ?>
      <li>
        <a href="<?php echo $action['link']; ?>" title="<?php echo $this->translate($action['title']); ?>"><img class="icon" src="<?php echo $this->baseUrl($action['icon']); ?>" alt="" /> <?php echo $this->translate($action['title']); ?></a>
      </li>
    <?php endforeach; ?>
  </ul>
</div>