<!-- Prompt users of IE 7 and lower to install Chrome Frame. -->
<!--[if lt IE 8]>
  <div class="alert-danger top-alert">
    <div class="alert alert-danger">
      <p><?php echo $this->translate('Your browser is'); ?><em> <?php echo $this->translate('ancient!'); ?></em> <a href="http://browsehappy.com/"><?php echo $this->translate('Upgrade to a different browser'); ?></a> <?php echo $this->translate('or'); ?> <a href="http://www.google.com/chromeframe/?redirect=true"><?php echo $this->translate('install Google Chrome Frame'); ?></a> <?php echo $this->translate('to experience this site.'); ?></p>
    </div>
  </div>
<![endif]-->