<nav id="actions-menu" class="well poped-in">
  <span class="arrow">&laquo;</span>
  <h5><?php echo $this->translate('Actions menu'); ?></h5>
  <ul class="nav nav-list">
    <?php foreach($this->actions as $action): ?>
      <?php if(empty($action['link'])): ?>
        <li class="nav-header"><?php echo $this->translate($action['label']); ?></li>
      <?php else: ?>
        <li>
          <a href="<?php echo $action['link']; ?>">
            <i class="<?php echo $action['icon']; ?> icon-fam"></i><span><?php echo $this->translate($this->translate($action['label'])); ?></span>
          </a>
        </li>
      <?php endif; ?>
    <?php endforeach; ?>
  </ul>
</nav>