<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_Document_Fragment_Partial extends \Application_Model_Document_Fragment_Partial implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getDirectName()
    {
        $this->__load();
        return parent::getDirectName();
    }

    public function getDirectLink()
    {
        $this->__load();
        return parent::getDirectLink();
    }

    public function getIconClass()
    {
        $this->__load();
        return parent::getIconClass();
    }

    public function getLineFrom()
    {
        $this->__load();
        return parent::getLineFrom();
    }

    public function getCharacterFrom()
    {
        $this->__load();
        return parent::getCharacterFrom();
    }

    public function getLineTo()
    {
        $this->__load();
        return parent::getLineTo();
    }

    public function getCharacterTo()
    {
        $this->__load();
        return parent::getCharacterTo();
    }

    public function setLineFrom($lineFrom)
    {
        $this->__load();
        return parent::setLineFrom($lineFrom);
    }

    public function setLineTo($lineTo)
    {
        $this->__load();
        return parent::setLineTo($lineTo);
    }

    public function setCharacterFrom($characterFrom)
    {
        $this->__load();
        return parent::setCharacterFrom($characterFrom);
    }

    public function setCharacterTo($characterTo)
    {
        $this->__load();
        return parent::setCharacterTo($characterTo);
    }

    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function created()
    {
        $this->__load();
        return parent::created();
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function getRatings()
    {
        $this->__load();
        return parent::getRatings();
    }

<<<<<<< HEAD
    public function geTags()
    {
        $this->__load();
        return parent::geTags();
=======
    public function getTags()
    {
        $this->__load();
        return parent::getTags();
>>>>>>> tien
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function getConversationTypes()
    {
        $this->__load();
        return parent::getConversationTypes();
    }

    public function isRatedByUser($user)
    {
        $this->__load();
        return parent::isRatedByUser($user);
    }

<<<<<<< HEAD
    public function getTags()
    {
        $this->__load();
        return parent::getTags();
=======
    public function geTags()
    {
        $this->__load();
        return parent::geTags();
>>>>>>> tien
    }

    public function getTagIds()
    {
        $this->__load();
        return parent::getTagIds();
    }

    public function addTag(\Application_Model_Tag $tag)
    {
        $this->__load();
        return parent::addTag($tag);
    }

    public function removeTag(\Application_Model_Tag $tag)
    {
        $this->__load();
        return parent::removeTag($tag);
    }

    public function setTags($tagIds = array (
))
    {
        $this->__load();
        return parent::setTags($tagIds);
    }

    public function clearTags()
    {
        $this->__load();
        return parent::clearTags();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'created', 'comments', 'tags', 'ratings', 'notifications', 'characterFrom', 'characterTo', 'lineFrom', 'lineTo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}