<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Application_Model_FileProxy extends \Application_Model_File implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function created()
    {
        $this->__load();
        return parent::created();
    }

    public function updated()
    {
        $this->__load();
        return parent::updated();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function getFilename()
    {
        $this->__load();
        return parent::getFilename();
    }

    public function getMimetype()
    {
        $this->__load();
        return parent::getMimetype();
    }

    public function getSize()
    {
        $this->__load();
        return parent::getSize();
    }

    public function getExtension()
    {
        $this->__load();
        return parent::getExtension();
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function getIsTarget()
    {
        $this->__load();
        return parent::getIsTarget();
    }

    public function setIsTarget($isTarget)
    {
        $this->__load();
        return parent::setIsTarget($isTarget);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'created', 'updated', 'filename', 'mimetype', 'size', 'location', 'extension', 'isTarget');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}